Feature/scheduled/fees metrics internal
LimeChain/hedera-services pull request #115
Opened 2021-01-08 10:44 UTC by Daniel-K-Ivanov

**Summary of the change**:
- Implementation for `hapi-fees` usage calculation of `Create`, `Sign`, `Delete` and `GetInfo` operations
- Implementation for `node` resource usage calculation for `Create`, `Sign`, `Delete` and `GetInfo` operations
- Added new `GlobalDynamicProperty` for `ledger.schedule.txExpiryTimeSecs` -> the time for which Scheduled TX expire

**External impacts**:
None.

**Applicable documentation**
- [ ] Javadoc
- [ ] HAPI protobuf comments
- [ ] README

2021-01-08 10:52 UTC, Daniel-K-Ivanov commented
Todo: verify the code coverage

2021-01-11 13:47 UTC, failfmi requested changes
All new files in `hapi-fees` should have a license for `Hedera Services API Fees`.

2021-01-11 13:47 UTC, failfmi commented on hapi-fees/src/main/java/com/hedera/services/usage/schedule/entities/ScheduleEntitySizes.java
> +package com.hedera.services.usage.schedule.entities;/*
The beginning of the license comment should be on the next line.

2021-01-11 13:47 UTC, failfmi commented on hapi-fees/src/test/java/com/hedera/services/usage/schedule/ScheduleCreateUsageTest.java
> +package com.hedera.services.usage.schedule;/*
The beginning of the license comment should be on the next line.

2021-01-11 13:47 UTC, failfmi commented on hapi-fees/src/test/java/com/hedera/services/usage/schedule/ScheduleDeleteUsageTest.java
> +package com.hedera.services.usage.schedule;/*
The beginning of the license comment should be on the next line.

2021-01-11 13:47 UTC, failfmi commented on hapi-fees/src/test/java/com/hedera/services/usage/schedule/ScheduleGetInfoUsageTest.java
> +package com.hedera.services.usage.schedule;/*
The beginning of the license comment should be on the next line.

2021-01-11 13:47 UTC, failfmi commented on hedera-node/src/main/java/com/hedera/services/context/AwareTransactionContext.java
> +	public void setCreated(ScheduleID id) { receiptConfig = receipt -> receipt.setScheduleID(id); }
A test for this is missing in `AwareTransactionContextTest.java`

2021-01-11 13:47 UTC, failfmi commented on hapi-fees/src/test/java/com/hedera/services/usage/schedule/ScheduleSignUsageTest.java
> +package com.hedera.services.usage.schedule;/*
The beginning of the license comment should be on the next line.

2021-01-11 13:47 UTC, failfmi commented on hapi-fees/src/test/java/com/hedera/services/usage/schedule/entities/ScheduleEntitySizesTest.java
> +package com.hedera.services.usage.schedule.entities;/*
The beginning of the license comment should be on the next line.

2021-01-11 13:47 UTC, failfmi commented on hedera-node/src/main/java/com/hedera/services/fees/calculation/schedule/queries/GetScheduleInfoResourceUsage.java
Tests in `GetScheduleInfoResourceUsageTest` are failing.

2021-01-11 17:12 UTC, georgiyazovaliiski approved these changes

2021-01-12 08:22 UTC, failfmi approved these changes
LGTM

2021-01-12 08:24 UTC, merged