Feature/scheduled transactions/tests
LimeChain/hedera-services pull request #126
Opened 2021-01-15 07:42 UTC by georgiyazovaliiski

Tests BDD

2021-01-15 13:58 UTC, Daniel-K-Ivanov requested changes

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on hedera-node/src/main/java/com/hedera/services/context/domain/security/PermissionFileUtils.java
> +		permissionKeys.put(ScheduleCreate, "scheduleCreate");
I think that we should see how to cover the new `schedule` ops in the `PermissionFileUtilsTest`

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
> +		try {
We should update the `StateViewTest` with unit tests for the `infoForSchedule` and `scheduleExists` methods

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
> +			var info = ScheduleInfo.newBuilder()
We should set the:
- `transactionBody`
- `signers`
as-well

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
> +					"Unexpected failure getting info for token {}!",
msg is copy-pasted

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on hedera-node/src/test/java/com/hedera/services/queries/crypto/GetAccountBalanceAnswerTest.java
>  	private void setup() {
I dont think that you need all those changes. Only the `scheduleStore` mock in order to add it in the constructor when you initialise `StateView`

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on hedera-node/src/test/java/com/hedera/services/txns/schedule/ScheduleDeleteTransitionLogicTest.java
> +        builder.setScheduleDelete(scheduleDelete.build());
nit: I think that this change is unnecessary

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on hedera-node/src/test/java/com/hedera/services/txns/schedule/ScheduleSignTransitionLogicTest.java
> +        SignaturePair.newBuilder().build();
I think that this change is unnecessary

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on test-clients/src/main/java/com/hedera/services/bdd/spec/queries/schedule/HapiGetScheduleInfo.java
> +
Add `Hedera Services Test Clients` license

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on test-clients/src/main/java/com/hedera/services/bdd/spec/queries/schedule/HapiGetScheduleInfo.java
> +    private static final Logger log = LogManager.getLogger(HapiGetTokenInfo.class);
logger is copy-pasted

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on test-clients/src/main/java/com/hedera/services/bdd/spec/queries/schedule/HapiGetScheduleInfo.java
> +    Optional<Timestamp> expectedExecuteAtTime = Optional.empty();
lets be consistent with the Protobufs and state and rename the `expectedSchedulingAccount` and `expectedPayer`. We should delete `expectedExecuteImmediately` and `expectedExecuteAtTime` as-well

We should add `adminKey` and `signers` as-well

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on test-clients/src/main/java/com/hedera/services/bdd/spec/queries/schedule/HapiGetScheduleInfo.java
> +
I think that we should check for `adminKey` and `signers` as-well

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on test-clients/src/main/java/com/hedera/services/bdd/spec/queries/schedule/HapiGetScheduleInfo.java
> +        return null;
self should return `this` rather than `null`

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnFactory.java
> +	}
I don't think this change is necessary

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleCreate.java
> +
Add license to this file

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleCreate.java
> +    public HederaFunctionality type() {
lets place the `override` after the properties

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleDelete.java
> +
Add license

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleDelete.java
> +    @Override
nit: place the override after the constructor

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleDelete.java
> +                spec -> spec.registry().getKey(effectivePayer(spec)));
I think that you should add the `adminKey` as a default signer as-well, otherwise TX will revert by default

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleSign.java
> +
Add license

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleSign.java
> +    @Override
- nit: type after constructor

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleCreateSpecs.java
> +
add license

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleDeleteSpecs.java
> +
add license

2021-01-15 13:58 UTC, Daniel-K-Ivanov commented on test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleSignSpecs.java
> +
add license

2021-01-18 13:54 UTC, failfmi approved these changes

2021-01-18 14:24 UTC, Daniel-K-Ivanov commented on hedera-node/src/test/java/com/hedera/services/queries/crypto/GetAccountBalanceAnswerTest.java
> +		scheduleStore = mock(ScheduleStore.class);
I think that this is the only line that you should add in this file.

2021-01-18 14:24 UTC, Daniel-K-Ivanov commented on test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleCreateSpecs.java
> +
We could add `TODO comment here` or remove it altogether

2021-01-19 08:01 UTC, Daniel-K-Ivanov approved these changes

2021-01-19 08:36 UTC, merged