Feature(state-view): TokenInfo types and max supply
LimeChain/hedera-services pull request #222
Opened 2021-05-19 15:56 UTC by failfmi

**Related issue(s)**:
Closes #168 
Closes #169 
Closes #170 

**Summary of the change**:
* `TokenInfo`: Set types and max supply
* E2E: assert valid set types

**External impacts**:
None.

**Applicable documentation**
- [ ] Javadoc
- [ ] HAPI protobuf comments
- [ ] README

2021-05-20 06:38 UTC, Daniel-K-Ivanov approved these changes

2021-05-20 08:17 UTC, joan41868 approved these changes

2021-05-25 05:15 UTC, Daniel-K-Ivanov requested changes
The following BDD tests could be implemented:
1) Token's supply type is correctly returned on `GetTokenInfo` queries - FINITE for `maxSupply` != 0 and `INFINITE` for `maxSupply=0`
2) Tokens cannot be created if `supply` type is `FINITE`, but `maxSupply` is `0`
3) Tokens cannot be created if `supply` type is `INFINITE`, but `maxSupply` is !=0

2021-05-25 05:15 UTC, Daniel-K-Ivanov commented on hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
>  			var info = TokenInfo.newBuilder()
1) We will have to add `supplyType` as-well
2) StateViewTest.java should be updated with checks for the new properties as-well

2021-05-25 05:15 UTC, Daniel-K-Ivanov commented on test-clients/src/main/java/com/hedera/services/bdd/spec/queries/token/HapiGetTokenInfo.java
> +	public HapiGetTokenInfo hasTokenType(TokenType t) {
we should add `hasSupplyType` method as-well

2021-05-25 05:15 UTC, Daniel-K-Ivanov commented on test-clients/src/main/java/com/hedera/services/bdd/spec/queries/token/HapiGetTokenInfo.java
>  		var actualInfo = response.getTokenGetInfo().getTokenInfo();
we should assert `tokenSupplyType` as-well

2021-05-25 05:15 UTC, Daniel-K-Ivanov commented on test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
> +								.maxSupply(1000)
Specifying only `maxSupply` without `supplyType` `FINITE` should result in an error

2021-05-25 14:18 UTC, Daniel-K-Ivanov approved these changes

2021-05-25 14:53 UTC, merged