+ increasing code coverage
LimeChain/hedera-services pull request #288
Opened 2021-06-22 07:59 UTC by daniel-danev-limechain

Signed-off-by: Daniel Danev <daniel.danev@limechain.tech>

**Related issue(s)**:
Closes #<issue number>

**Summary of the change**:
Lorem ipsum dolor sit amet.

**External impacts**:
None.

**Applicable documentation**
- [ ] Javadoc
- [ ] HAPI protobuf comments
- [ ] README

2021-06-24 10:56 UTC, joan41868 approved these changes

2021-06-28 11:02 UTC, Daniel-K-Ivanov requested changes

2021-06-28 11:02 UTC, Daniel-K-Ivanov commented on hedera-node/src/test/java/com/hedera/services/store/models/AccountTest.java
> +		assertEquals(-1217798680, actualResult);
Normally when you test hashCode you create another instance of the subject class and verify that if the same properties are populated the hashcode is equal. The test you wrote will brake if you add another property. 

My assumption is that you executed `hashCode` and saw what the output is and then placed the number here, which is basically testing the code with the output from the code and that's not meaningful

2021-06-28 13:16 UTC, Daniel-K-Ivanov approved these changes

2021-06-28 13:25 UTC, merged