Added tests from Call/CallLocal/CreateEvmTxProcessor
LimeChain/hedera-services pull request #544
Opened 2021-09-30 13:11 UTC by rusiboyadjiev

Signed-off-by: Rusi Boyadjiev <rusiboyadjiev@gmail.com>

2021-09-30 13:35 UTC, Daniel-K-Ivanov commented on hedera-node/src/test/java/com/hedera/services/txns/contract/process/CallEvmTxProcessorTest.java
> +package com.hedera.services.txns.contract.process;
Missing license

2021-09-30 13:35 UTC, Daniel-K-Ivanov commented on hedera-node/src/test/java/com/hedera/services/txns/contract/process/CallLocalEvmTxProcessorTest.java
> +package com.hedera.services.txns.contract.process;
Missing license

2021-09-30 13:35 UTC, Daniel-K-Ivanov commented on hedera-node/src/test/java/com/hedera/services/txns/contract/process/CreateEvmTxProcessorTest.java
> +package com.hedera.services.txns.contract.process;
Missing license

2021-10-01 05:41 UTC, failfmi commented
Can we add two more tests in Create and Call for the following lines in `EvmTxProcessor`
```java
if (intrinsicGas.toLong() > gasLimit) {
	throw new InvalidTransactionException(gasLimit < dynamicProperties.maxGas() ? INSUFFICIENT_GAS : MAX_GAS_LIMIT_EXCEEDED);
}
```

2021-10-01 05:48 UTC, failfmi requested changes
Can we add two more tests in Create and Call for the following lines in `EvmTxProcessor`
```java
if (intrinsicGas.toLong() > gasLimit) {
	throw new InvalidTransactionException(gasLimit < dynamicProperties.maxGas() ? INSUFFICIENT_GAS : MAX_GAS_LIMIT_EXCEEDED);
}
```

2021-10-04 06:06 UTC, failfmi approved these changes

2021-10-04 06:06 UTC, merged