Refactoring of `FreezeTransitionLogic`
LimeChain/hedera-services pull request #548
Opened 2021-10-01 09:13 UTC by joan41868

### Description:

This **PR** provides refactoring of the `FreezeTransitionLogic`, which freezes the network for a given timespan.

The refactoring's aim is to use `InvalidTransactionException` in order to abort invalid transactions.

2021-10-01 14:17 UTC, georgiyazovaliiski requested changes

2021-10-01 14:17 UTC, georgiyazovaliiski commented on hedera-node/src/main/java/com/hedera/services/legacy/handler/FreezeHandler.java
> + * transactions. Documentation available at index.html#proto.FreezeTransactionBody
Nit: Can we undo this.

2021-10-01 14:17 UTC, georgiyazovaliiski commented on hedera-node/src/test/java/com/hedera/services/txns/network/FreezeTransitionLogicTest.java
> +//		given(delegate.perform(freezeTxn, consensusTime)).willReturn(freezeRec);
Why is this commented? Should it be replaced by some other assertion?

2021-10-01 14:17 UTC, georgiyazovaliiski commented on hedera-node/src/test/java/com/hedera/services/txns/network/FreezeTransitionLogicTest.java
> +//		given(delegate.perform(freezeTxn, consensusTime)).willReturn(freezeRec);
Why is this commented? Should it be replaced by some other assertion?

2021-10-01 14:17 UTC, georgiyazovaliiski commented on hedera-node/src/test/java/com/hedera/services/txns/network/FreezeTransitionLogicTest.java
> +//		given(delegate.perform(any(), any())).willThrow(IllegalStateException.class);
Why is this commented? Should it be replaced by some other assertion?

2021-10-04 05:46 UTC, CordonaCodeCraft approved these changes
OLGTM

2021-10-12 10:05 UTC, merged