Docs(token): add error clarification on freeze/unfreeze/grantKYC/revo…
LimeChain/hedera-services pull request #55
Opened 2020-09-23 12:45 UTC by failfmi

**Related issue(s)**:
Closes #46 

**Summary of the change**:
- add error clarification on freeze/unfreeze/grantKYC/revokeKYC/wipe
- ignore `HAPI.html` for Association related protobufs.

**Applicable documentation**
- [ ] Javadoc
- [x] HAPI protobuf comments
- [ ] README

2020-09-23 15:00 UTC, Daniel-K-Ivanov requested changes

2020-09-23 15:55 UTC, failfmi commented on hapi-proto/src/main/proto/TokenWipeAccount.proto
>   If the provided account does not have a relation with the provided Token, transaction results in ACCOUNT_HAS_NO_TOKEN_RELATIONSHIP.
`ACCOUNT_HAS_NO_TOKEN_RELATIONSHIP` has been transformed to `TOKEN_NOT_ASSOCIATED_TO_ACCOUNT`

2020-09-24 06:23 UTC, Daniel-K-Ivanov approved these changes

2020-09-24 06:25 UTC, georgiyazovaliiski approved these changes
All description updates look understandable and clear.

2020-09-24 06:39 UTC, merged