Coverage Bump: Stream, State and ServicesState.java
LimeChain/hedera-services pull request #653
Opened 2021-10-26 05:32 UTC by georgiyazovaliiski

This PR bumps the coverage of the Stream, State packages + the ServicesState.java file.

**Special Notes**
There are 2 TODOs which have sparked a discussion about token transfers and how the SDK sends information to the `services` part of the project.

Closes: #637 #638

2021-10-31 18:03 UTC, joan41868 approved these changes

2021-11-01 12:09 UTC, Daniel-K-Ivanov requested changes

2021-11-01 12:09 UTC, Daniel-K-Ivanov commented on hedera-node/src/main/java/com/hedera/services/state/submerkle/ExpirableTxnRecord.java
> +							tokenAdjustments.size() > i ? tokenAdjustments.get(i) : nftTokenAdjustments.get(i - tokenAdjustments.size())))
Shouldn't there be a check for whether this is empty or not?

2021-11-01 12:09 UTC, Daniel-K-Ivanov commented on hedera-node/src/test/java/com/hedera/services/state/submerkle/NftAdjustmentsTest.java
> +		assertNotEquals(subject, null);
Shouldn't this be `null`, `subject`?

2021-11-03 13:47 UTC, Daniel-K-Ivanov approved these changes

2021-11-03 13:50 UTC, merged