Coverage increase: Contracts package
LimeChain/hedera-services pull request #656
Opened 2021-10-27 11:17 UTC by alshapi

**Description**:
This PR increases the unit tests coverage of the Contracts package.

**Related issue(s)**:

Closes #639

- [x] Tested (unit, integration, etc.)

2021-10-30 09:43 UTC, georgiyazovaliiski requested changes

2021-10-30 09:43 UTC, georgiyazovaliiski commented on hedera-node/src/main/java/com/hedera/services/contracts/execution/EvmTxProcessor.java
> +				//hardly testable, since the Type enum is not extendable and has fixed values
remove comment

2021-10-30 09:43 UTC, georgiyazovaliiski commented on hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaSelfDestructOperation.java
> +			//hardly testable
remove comment if not going to test this one

2021-11-01 11:02 UTC, alshapi commented on hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaSelfDestructOperation.java
>  			return super.execute(frame, evm);
We reach the line, but then the real method in the superclass is executed and the test fails

2021-11-02 07:57 UTC, joan41868 requested changes
Let's address the changes which @georgiyazovaliiski listed.

2021-11-02 08:56 UTC, merged