Precompiles: include contract function result
LimeChain/hedera-services pull request #794
Opened 2022-01-18 12:24 UTC by dimitar-dinev

Included contract function result in child record and extended assertions.

2022-01-20 10:31 UTC, stoqnkpL requested changes
Changes required before we can open a PR to Hedera master:
- update with latest changes from hedera master
- fix failing unit tests (mvn clean install without the -DskipTests=true flag results in Unit test failures)
- resolve the PR comments

2022-01-20 10:31 UTC, stoqnkpL commented on hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiringCreations.java
> +				Address.fromHexString(HTS_PRECOMPILED_CONTRACT_ADDRESS)))
The `contractId` in child records is 359, which is the decimal representation of the hexadecimal address `167`. I think we should convert it to a Hedera account address using the EntityIdUtils methods

2022-01-20 10:31 UTC, stoqnkpL commented on hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiringCreations.java
> +			contractFunctionResult.setContractCallResult(ByteString.copyFrom(SerializationUtils.serialize(sideEffectsTracker.getTrackedNftMints().toArray())));
I'm not sure this is correct, the values I observe in child records looks like this:
```
  contractCallResult: "\254\355\000\005ur\000\023[Ljava.lang.Object;\220\316X\237\020s)l\002\000\000xp\000\000\000\001sr\000\016java.lang.Long;\213\344\220\314\217#\337\002\000\001J\000\005valuexr\000\020java.lang.Number\206\254\225\035\v\224\340\213\002\000\000xp\000\000\000\000\000\000\000\001"
```
We shouldn't have java objects here, rather the Bytes that are returned to the solidity contract by the precompile execution.

2022-01-21 14:44 UTC, georgiyazovaliiski commented on test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractFnResultAsserts.java
> +					"Wrong contract call result!");
Here we can do `Assertions.equals()` and simply compare the ByteString objects, without parsing them to `toByteArray()`

2022-01-21 14:45 UTC, georgiyazovaliiski commented on test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSSuite.java
> +											.withSerialNumbers(1L)
Format this block so that resultWith() is on a new line and fix the indentation. (tabs)

2022-01-21 14:46 UTC, georgiyazovaliiski commented on test-clients/src/main/java/com/hedera/services/bdd/suites/utils/precompile/FunctionResult.java
> +		MINT, BURN, TRANSFER, ASSOCIATE, DISASSOCIATE
I think you don't need all these new statuses

2022-01-21 14:48 UTC, georgiyazovaliiski commented on test-clients/src/main/java/com/hedera/services/bdd/suites/utils/precompile/FunctionResult.java
> +			return Bytes.wrap(tupleType.encode(result).array());
This whole block of code can be simplified significantly.
`
Tuple result;
			if (functionType == FunctionType.MINT) {
				result = Tuple.of(status.getNumber(), BigInteger.valueOf(totalSupply), serialNumbers);
			} else if (functionType == FunctionType.BURN) {
				result = Tuple.of(status.getNumber(), BigInteger.valueOf(totalSupply));
			} else {
			        return UInt256.valueOf(status.getNumber());
                         }
			return Bytes.wrap(tupleType.encode(result).array());
`

2022-01-21 14:52 UTC, georgiyazovaliiski commented on test-clients/src/main/java/com/hedera/services/bdd/suites/utils/precompile/FunctionResult.java
> +		}
Maybe modify this `else` to be an `else if (functionType == FunctionType.BURN)` in order to cover for the rest of the cases where FunctionType is neither MINT nor BURN.

2022-01-21 14:52 UTC, georgiyazovaliiski requested changes
Overall looks great, address the comments and we might be ready for merge.

2022-01-24 08:38 UTC, stoqnkpL reviewed
Looks good!
We need to merge the changes from `hedera/master` though, there's a commit from Friday with changes in `HTSPrecompiledContract` that conflict.

2022-01-25 13:27 UTC, georgiyazovaliiski approved these changes

2022-01-25 13:47 UTC, stoqnkpL approved these changes
LGTM!

2022-01-25 13:48 UTC, merged